#!/usr/bin/env bash
# Build the single Tailwind stylesheet that ships in frontend/dist/.
#
# This is the ONLY step that needs network access, and its output is committed
# so a clone runs fully offline. Re-run it after editing frontend/src/css/ or
# adding classes to the JS panels.
set -euo pipefail

cd "$(dirname "$0")/.."

TAILWIND_VERSION="3.4.17"   # pinned: the committed CSS must be reproducible
IN="frontend/src/css/input.css"
OUT="frontend/dist/css/strix-dash.css"

mkdir -p "$(dirname "$OUT")"

if ! command -v npx >/dev/null 2>&1; then
    echo "error: npx not found. Install nodejs/npm, or copy a prebuilt $OUT." >&2
    exit 1
fi

echo "Building $OUT with tailwindcss@${TAILWIND_VERSION}..."
npx --yes "tailwindcss@${TAILWIND_VERSION}" \
    --config tailwind.config.js \
    --input "$IN" \
    --output "$OUT" \
    --minify

# Record provenance in the artifact itself, so "why does this look different?"
# is answerable a year from now without digging through git history.
header="/* strix-dash stylesheet — generated by scripts/build-css.sh
   tailwindcss ${TAILWIND_VERSION} — built $(date -u +%Y-%m-%dT%H:%M:%SZ)
   Do not edit directly; edit ${IN} and re-run this script. */
"
printf '%s' "$header" | cat - "$OUT" > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT") bytes)"
